CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    display_name VARCHAR(255),
    created_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);